<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'mobile_code' => '+93', 'mobile_length' => 9],
            ['name' => 'Albania', 'mobile_code' => '+355', 'mobile_length' => 9],
            ['name' => 'Algeria', 'mobile_code' => '+213', 'mobile_length' => 9],
            ['name' => 'American Samoa', 'mobile_code' => '+1-684', 'mobile_length' => 7],
            ['name' => 'Andorra', 'mobile_code' => '+376', 'mobile_length' => 6],
            ['name' => 'Angola', 'mobile_code' => '+244', 'mobile_length' => 9],
            ['name' => 'Anguilla', 'mobile_code' => '+1-264', 'mobile_length' => 7],
            ['name' => 'Antarctica', 'mobile_code' => '+672', 'mobile_length' => 4],
            ['name' => 'Antigua And Barbuda', 'mobile_code' => '+1-268', 'mobile_length' => 7],
            ['name' => 'Argentina', 'mobile_code' => '+54', 'mobile_length' => 10],
            ['name' => 'Armenia', 'mobile_code' => '+374', 'mobile_length' => 8],
            ['name' => 'Aruba', 'mobile_code' => '+297', 'mobile_length' => 7],
            ['name' => 'Australia', 'mobile_code' => '+61', 'mobile_length' => 9],
            ['name' => 'Austria', 'mobile_code' => '+43', 'mobile_length' => 9],
            ['name' => 'Azerbaijan', 'mobile_code' => '+994', 'mobile_length' => 9],
            ['name' => 'Bahamas', 'mobile_code' => '+1-242', 'mobile_length' => 7],
            ['name' => 'Bahrain', 'mobile_code' => '+973', 'mobile_length' => 8],
            ['name' => 'Bangladesh', 'mobile_code' => '+880', 'mobile_length' => 11],
            ['name' => 'Barbados', 'mobile_code' => '+1-246', 'mobile_length' => 7],
            ['name' => 'Belarus', 'mobile_code' => '+375', 'mobile_length' => 9],
            ['name' => 'Belgium', 'mobile_code' => '+32', 'mobile_length' => 9],
            ['name' => 'Belize', 'mobile_code' => '+501', 'mobile_length' => 7],
            ['name' => 'Benin', 'mobile_code' => '+229', 'mobile_length' => 8],
            ['name' => 'Bermuda', 'mobile_code' => '+1-441', 'mobile_length' => 7],
            ['name' => 'Bhutan', 'mobile_code' => '+975', 'mobile_length' => 8],
            ['name' => 'Bolivia', 'mobile_code' => '+591', 'mobile_length' => 8],
            ['name' => 'Bosnia And Herzegovina', 'mobile_code' => '+387', 'mobile_length' => 8],
            ['name' => 'Botswana', 'mobile_code' => '+267', 'mobile_length' => 7],
            ['name' => 'Bouvet Island', 'mobile_code' => '+47', 'mobile_length' => 8],
            ['name' => 'Brazil', 'mobile_code' => '+55', 'mobile_length' => 11],
            ['name' => 'British Indian Ocean Territory', 'mobile_code' => '+246', 'mobile_length' => 7],
            ['name' => 'Brunei Darussalam', 'mobile_code' => '+673', 'mobile_length' => 7],
            ['name' => 'Bulgaria', 'mobile_code' => '+359', 'mobile_length' => 9],
            ['name' => 'Burkina Faso', 'mobile_code' => '+226', 'mobile_length' => 8],
            ['name' => 'Burundi', 'mobile_code' => '+257', 'mobile_length' => 8],
            ['name' => 'Cambodia', 'mobile_code' => '+855', 'mobile_length' => 9],
            ['name' => 'Cameroon', 'mobile_code' => '+237', 'mobile_length' => 9],
            ['name' => 'Canada', 'mobile_code' => '+1', 'mobile_length' => 10],
            ['name' => 'Cape Verde', 'mobile_code' => '+238', 'mobile_length' => 7],
            ['name' => 'Cayman Islands', 'mobile_code' => '+1-345', 'mobile_length' => 7],
            ['name' => 'Central African Republic', 'mobile_code' => '+236', 'mobile_length' => 8],
            ['name' => 'Chad', 'mobile_code' => '+235', 'mobile_length' => 8],
            ['name' => 'Chile', 'mobile_code' => '+56', 'mobile_length' => 9],
            ['name' => 'China', 'mobile_code' => '+86', 'mobile_length' => 11],
            ['name' => 'Christmas Island', 'mobile_code' => '+61', 'mobile_length' => 9],
            ['name' => 'Cocos (Keeling) Islands', 'mobile_code' => '+61', 'mobile_length' => 9],
            ['name' => 'Colombia', 'mobile_code' => '+57', 'mobile_length' => 10],
            ['name' => 'Comoros', 'mobile_code' => '+269', 'mobile_length' => 7],
            ['name' => 'Congo', 'mobile_code' => '+242', 'mobile_length' => 8],
            ['name' => 'Congo, Democratic Republic', 'mobile_code' => '+243', 'mobile_length' => 9],
            ['name' => 'Cook Islands', 'mobile_code' => '+682', 'mobile_length' => 7],
            ['name' => 'Costa Rica', 'mobile_code' => '+506', 'mobile_length' => 8],
            ['name' => 'Cote D\'Ivoire', 'mobile_code' => '+225', 'mobile_length' => 8],
            ['name' => 'Croatia', 'mobile_code' => '+385', 'mobile_length' => 9],
            ['name' => 'Cuba', 'mobile_code' => '+53', 'mobile_length' => 8],
            ['name' => 'Cyprus', 'mobile_code' => '+357', 'mobile_length' => 8],
            ['name' => 'Czech Republic', 'mobile_code' => '+420', 'mobile_length' => 9],
            ['name' => 'Denmark', 'mobile_code' => '+45', 'mobile_length' => 8],
            ['name' => 'Djibouti', 'mobile_code' => '+253', 'mobile_length' => 8],
            ['name' => 'Dominica', 'mobile_code' => '+1-767', 'mobile_length' => 7],
            ['name' => 'Dominican Republic', 'mobile_code' => '+1-809', 'mobile_length' => 7],
            ['name' => 'Ecuador', 'mobile_code' => '+593', 'mobile_length' => 9],
            ['name' => 'Egypt', 'mobile_code' => '+20', 'mobile_length' => 10],
            ['name' => 'El Salvador', 'mobile_code' => '+503', 'mobile_length' => 8],
            ['name' => 'Equatorial Guinea', 'mobile_code' => '+240', 'mobile_length' => 9],
            ['name' => 'Eritrea', 'mobile_code' => '+291', 'mobile_length' => 8],
            ['name' => 'Estonia', 'mobile_code' => '+372', 'mobile_length' => 9],
            ['name' => 'Ethiopia', 'mobile_code' => '+251', 'mobile_length' => 9],
            ['name' => 'Falkland Islands (Malvinas)', 'mobile_code' => '+500', 'mobile_length' => 7],
            ['name' => 'Faroe Islands', 'mobile_code' => '+298', 'mobile_length' => 7],
            ['name' => 'Fiji', 'mobile_code' => '+679', 'mobile_length' => 7],
            ['name' => 'Finland', 'mobile_code' => '+358', 'mobile_length' => 9],
            ['name' => 'France', 'mobile_code' => '+33', 'mobile_length' => 9],
            ['name' => 'French Guiana', 'mobile_code' => '+594', 'mobile_length' => 9],
            ['name' => 'French Polynesia', 'mobile_code' => '+689', 'mobile_length' => 8],
            ['name' => 'French Southern Territories', 'mobile_code' => '+262', 'mobile_length' => 9],
            ['name' => 'Gabon', 'mobile_code' => '+241', 'mobile_length' => 9],
            ['name' => 'Gambia', 'mobile_code' => '+220', 'mobile_length' => 7],
            ['name' => 'Georgia', 'mobile_code' => '+995', 'mobile_length' => 9],
            ['name' => 'Germany', 'mobile_code' => '+49', 'mobile_length' => 10],
            ['name' => 'Ghana', 'mobile_code' => '+233', 'mobile_length' => 9],
            ['name' => 'Gibraltar', 'mobile_code' => '+350', 'mobile_length' => 8],
            ['name' => 'Greece', 'mobile_code' => '+30', 'mobile_length' => 10],
            ['name' => 'Greenland', 'mobile_code' => '+299', 'mobile_length' => 6],
            ['name' => 'Grenada', 'mobile_code' => '+1-473', 'mobile_length' => 10],
            ['name' => 'Guadeloupe', 'mobile_code' => '+590', 'mobile_length' => 9],
            ['name' => 'Guam', 'mobile_code' => '+1-671', 'mobile_length' => 10],
            ['name' => 'Guatemala', 'mobile_code' => '+502', 'mobile_length' => 8],
            ['name' => 'Guernsey', 'mobile_code' => '+44', 'mobile_length' => 10],
            ['name' => 'Guinea', 'mobile_code' => '+224', 'mobile_length' => 9],
            ['name' => 'Guinea-Bissau', 'mobile_code' => '+245', 'mobile_length' => 7],
            ['name' => 'Guyana', 'mobile_code' => '+592', 'mobile_length' => 7],
            ['name' => 'Haiti', 'mobile_code' => '+509', 'mobile_length' => 8],
            ['name' => 'Honduras', 'mobile_code' => '+504', 'mobile_length' => 8],
            ['name' => 'Hong Kong', 'mobile_code' => '+852', 'mobile_length' => 8],
            ['name' => 'Hungary', 'mobile_code' => '+36', 'mobile_length' => 9],
            ['name' => 'Iceland', 'mobile_code' => '+354', 'mobile_length' => 7],
            ['name' => 'India', 'mobile_code' => '+91', 'mobile_length' => 10],
            ['name' => 'Indonesia', 'mobile_code' => '+62', 'mobile_length' => 11],
            ['name' => 'Iran', 'mobile_code' => '+98', 'mobile_length' => 10],
            ['name' => 'Iraq', 'mobile_code' => '+964', 'mobile_length' => 10],
            ['name' => 'Ireland', 'mobile_code' => '+353', 'mobile_length' => 9],
            ['name' => 'Isle of Man', 'mobile_code' => '+44', 'mobile_length' => 10],
            ['name' => 'Israel', 'mobile_code' => '+972', 'mobile_length' => 9],
            ['name' => 'Italy', 'mobile_code' => '+39', 'mobile_length' => 10],
            ['name' => 'Jamaica', 'mobile_code' => '+1-876', 'mobile_length' => 10],
            ['name' => 'Japan', 'mobile_code' => '+81', 'mobile_length' => 10],
            ['name' => 'Jersey', 'mobile_code' => '+44', 'mobile_length' => 10],
            ['name' => 'Jordan', 'mobile_code' => '+962', 'mobile_length' => 9],
            ['name' => 'Kazakhstan', 'mobile_code' => '+7', 'mobile_length' => 10],
            ['name' => 'Kenya', 'mobile_code' => '+254', 'mobile_length' => 10],
            ['name' => 'Kiribati', 'mobile_code' => '+686', 'mobile_length' => 8],
            ['name' => 'Kuwait', 'mobile_code' => '+965', 'mobile_length' => 8],
            ['name' => 'Kyrgyzstan', 'mobile_code' => '+996', 'mobile_length' => 9],
            ['name' => 'Laos', 'mobile_code' => '+856', 'mobile_length' => 10],
            ['name' => 'Latvia', 'mobile_code' => '+371', 'mobile_length' => 8],
            ['name' => 'Lebanon', 'mobile_code' => '+961', 'mobile_length' => 8],
            ['name' => 'Lesotho', 'mobile_code' => '+266', 'mobile_length' => 8],
            ['name' => 'Liberia', 'mobile_code' => '+231', 'mobile_length' => 7],
            ['name' => 'Libya', 'mobile_code' => '+218', 'mobile_length' => 9],
            ['name' => 'Liechtenstein', 'mobile_code' => '+423', 'mobile_length' => 9],
            ['name' => 'Lithuania', 'mobile_code' => '+370', 'mobile_length' => 8],
            ['name' => 'Luxembourg', 'mobile_code' => '+352', 'mobile_length' => 9],
            ['name' => 'Macau', 'mobile_code' => '+853', 'mobile_length' => 8],
            ['name' => 'Madagascar', 'mobile_code' => '+261', 'mobile_length' => 9],
            ['name' => 'Malawi', 'mobile_code' => '+265', 'mobile_length' => 9],
            ['name' => 'Malaysia', 'mobile_code' => '+60', 'mobile_length' => 10],
            ['name' => 'Maldives', 'mobile_code' => '+960', 'mobile_length' => 7],
            ['name' => 'Mali', 'mobile_code' => '+223', 'mobile_length' => 8],
            ['name' => 'Malta', 'mobile_code' => '+356', 'mobile_length' => 8],
            ['name' => 'Marshall Islands', 'mobile_code' => '+692', 'mobile_length' => 7],
            ['name' => 'Martinique', 'mobile_code' => '+596', 'mobile_length' => 9],
            ['name' => 'Mauritania', 'mobile_code' => '+222', 'mobile_length' => 9],
            ['name' => 'Mauritius', 'mobile_code' => '+230', 'mobile_length' => 8],
            ['name' => 'Mexico', 'mobile_code' => '+52', 'mobile_length' => 10],
            ['name' => 'Micronesia', 'mobile_code' => '+691', 'mobile_length' => 7],
            ['name' => 'Moldova', 'mobile_code' => '+373', 'mobile_length' => 8],
            ['name' => 'Monaco', 'mobile_code' => '+377', 'mobile_length' => 9],
            ['name' => 'Mongolia', 'mobile_code' => '+976', 'mobile_length' => 8],
            ['name' => 'Montenegro', 'mobile_code' => '+382', 'mobile_length' => 8],
            ['name' => 'Montserrat', 'mobile_code' => '+1-664', 'mobile_length' => 10],
            ['name' => 'Morocco', 'mobile_code' => '+212', 'mobile_length' => 9],
            ['name' => 'Mozambique', 'mobile_code' => '+258', 'mobile_length' => 9],
            ['name' => 'Myanmar', 'mobile_code' => '+95', 'mobile_length' => 9],
            ['name' => 'Namibia', 'mobile_code' => '+264', 'mobile_length' => 9],
            ['name' => 'Nauru', 'mobile_code' => '+674', 'mobile_length' => 7],
            ['name' => 'Nepal', 'mobile_code' => '+977', 'mobile_length' => 10],
            ['name' => 'Netherlands', 'mobile_code' => '+31', 'mobile_length' => 9],
            ['name' => 'New Caledonia', 'mobile_code' => '+687', 'mobile_length' => 6],
            ['name' => 'New Zealand', 'mobile_code' => '+64', 'mobile_length' => 9],
            ['name' => 'Nicaragua', 'mobile_code' => '+505', 'mobile_length' => 8],
            ['name' => 'Niger', 'mobile_code' => '+227', 'mobile_length' => 8],
            ['name' => 'Nigeria', 'mobile_code' => '+234', 'mobile_length' => 10],
            ['name' => 'Niue', 'mobile_code' => '+683', 'mobile_length' => 4],
            ['name' => 'Norfolk Island', 'mobile_code' => '+672', 'mobile_length' => 6],
            ['name' => 'North Korea', 'mobile_code' => '+850', 'mobile_length' => 10],
            ['name' => 'North Macedonia', 'mobile_code' => '+389', 'mobile_length' => 8],
            ['name' => 'Norway', 'mobile_code' => '+47', 'mobile_length' => 8],
            ['name' => 'Oman', 'mobile_code' => '+968', 'mobile_length' => 8],
            ['name' => 'Pakistan', 'mobile_code' => '+92', 'mobile_length' => 10],
            ['name' => 'Palau', 'mobile_code' => '+680', 'mobile_length' => 7],
            ['name' => 'Palestine', 'mobile_code' => '+970', 'mobile_length' => 9],
            ['name' => 'Panama', 'mobile_code' => '+507', 'mobile_length' => 8],
            ['name' => 'Papua New Guinea', 'mobile_code' => '+675', 'mobile_length' => 8],
            ['name' => 'Paraguay', 'mobile_code' => '+595', 'mobile_length' => 9],
            ['name' => 'Peru', 'mobile_code' => '+51', 'mobile_length' => 9],
            ['name' => 'Philippines', 'mobile_code' => '+63', 'mobile_length' => 10],
            ['name' => 'Pitcairn', 'mobile_code' => '+64', 'mobile_length' => 10],
            ['name' => 'Poland', 'mobile_code' => '+48', 'mobile_length' => 9],
            ['name' => 'Portugal', 'mobile_code' => '+351', 'mobile_length' => 9],
            ['name' => 'Puerto Rico', 'mobile_code' => '+1-787', 'mobile_length' => 10],
            ['name' => 'Qatar', 'mobile_code' => '+974', 'mobile_length' => 8],
            ['name' => 'Réunion', 'mobile_code' => '+262', 'mobile_length' => 9],
            ['name' => 'Romania', 'mobile_code' => '+40', 'mobile_length' => 10],
            ['name' => 'Russia', 'mobile_code' => '+7', 'mobile_length' => 10],
            ['name' => 'Rwanda', 'mobile_code' => '+250', 'mobile_length' => 9],
            ['name' => 'Saint Barthélemy', 'mobile_code' => '+590', 'mobile_length' => 9],
            ['name' => 'Saint Helena', 'mobile_code' => '+290', 'mobile_length' => 4],
            ['name' => 'Saint Kitts and Nevis', 'mobile_code' => '+1-869', 'mobile_length' => 10],
            ['name' => 'Saint Lucia', 'mobile_code' => '+1-758', 'mobile_length' => 10],
            ['name' => 'Saint Martin', 'mobile_code' => '+590', 'mobile_length' => 9],
            ['name' => 'Saint Pierre and Miquelon', 'mobile_code' => '+508', 'mobile_length' => 6],
            ['name' => 'Saint Vincent and the Grenadines', 'mobile_code' => '+1-784', 'mobile_length' => 10],
            ['name' => 'Samoa', 'mobile_code' => '+685', 'mobile_length' => 7],
            ['name' => 'San Marino', 'mobile_code' => '+378', 'mobile_length' => 9],
            ['name' => 'São Tomé and Príncipe', 'mobile_code' => '+239', 'mobile_length' => 7],
            ['name' => 'Saudi Arabia', 'mobile_code' => '+966', 'mobile_length' => 9],
            ['name' => 'Senegal', 'mobile_code' => '+221', 'mobile_length' => 9],
            ['name' => 'Serbia', 'mobile_code' => '+381', 'mobile_length' => 9],
            ['name' => 'Seychelles', 'mobile_code' => '+248', 'mobile_length' => 7],
            ['name' => 'Sierra Leone', 'mobile_code' => '+232', 'mobile_length' => 8],
            ['name' => 'Singapore', 'mobile_code' => '+65', 'mobile_length' => 8],
            ['name' => 'Sint Maarten', 'mobile_code' => '+1-721', 'mobile_length' => 10],
            ['name' => 'Slovakia', 'mobile_code' => '+421', 'mobile_length' => 9],
            ['name' => 'Slovenia', 'mobile_code' => '+386', 'mobile_length' => 9],
            ['name' => 'Solomon Islands', 'mobile_code' => '+677', 'mobile_length' => 7],
            ['name' => 'Somalia', 'mobile_code' => '+252', 'mobile_length' => 9],
            ['name' => 'South Africa', 'mobile_code' => '+27', 'mobile_length' => 9],
            ['name' => 'South Korea', 'mobile_code' => '+82', 'mobile_length' => 10],
            ['name' => 'South Sudan', 'mobile_code' => '+211', 'mobile_length' => 9],
            ['name' => 'Spain', 'mobile_code' => '+34', 'mobile_length' => 9],
            ['name' => 'Sri Lanka', 'mobile_code' => '+94', 'mobile_length' => 9],
            ['name' => 'Sudan', 'mobile_code' => '+249', 'mobile_length' => 9],
            ['name' => 'Suriname', 'mobile_code' => '+597', 'mobile_length' => 7],
            ['name' => 'Svalbard and Jan Mayen', 'mobile_code' => '+47', 'mobile_length' => 8],
            ['name' => 'Sweden', 'mobile_code' => '+46', 'mobile_length' => 9],
            ['name' => 'Switzerland', 'mobile_code' => '+41', 'mobile_length' => 9],
            ['name' => 'Syria', 'mobile_code' => '+963', 'mobile_length' => 9],
            ['name' => 'Taiwan', 'mobile_code' => '+886', 'mobile_length' => 9],
            ['name' => 'Tajikistan', 'mobile_code' => '+992', 'mobile_length' => 9],
            ['name' => 'Tanzania', 'mobile_code' => '+255', 'mobile_length' => 9],
            ['name' => 'Thailand', 'mobile_code' => '+66', 'mobile_length' => 9],
            ['name' => 'Timor-Leste', 'mobile_code' => '+670', 'mobile_length' => 8],
            ['name' => 'Togo', 'mobile_code' => '+228', 'mobile_length' => 8],
            ['name' => 'Tokelau', 'mobile_code' => '+690', 'mobile_length' => 4],
            ['name' => 'Tonga', 'mobile_code' => '+676', 'mobile_length' => 7],
            ['name' => 'Trinidad and Tobago', 'mobile_code' => '+1-868', 'mobile_length' => 10],
            ['name' => 'Tunisia', 'mobile_code' => '+216', 'mobile_length' => 8],
            ['name' => 'Turkey', 'mobile_code' => '+90', 'mobile_length' => 10],
            ['name' => 'Turkmenistan', 'mobile_code' => '+993', 'mobile_length' => 8],
            ['name' => 'Tuvalu', 'mobile_code' => '+688', 'mobile_length' => 5],
            ['name' => 'Uganda', 'mobile_code' => '+256', 'mobile_length' => 9],
            ['name' => 'Ukraine', 'mobile_code' => '+380', 'mobile_length' => 9],
            ['name' => 'United Arab Emirates', 'mobile_code' => '+971', 'mobile_length' => 9],
            ['name' => 'United Kingdom', 'mobile_code' => '+44', 'mobile_length' => 10],
            ['name' => 'United States', 'mobile_code' => '+1', 'mobile_length' => 10],
            ['name' => 'Uruguay', 'mobile_code' => '+598', 'mobile_length' => 9],
            ['name' => 'Uzbekistan', 'mobile_code' => '+998', 'mobile_length' => 9],
            ['name' => 'Vanuatu', 'mobile_code' => '+678', 'mobile_length' => 7],
            ['name' => 'Vatican City', 'mobile_code' => '+379', 'mobile_length' => 8],
            ['name' => 'Venezuela', 'mobile_code' => '+58', 'mobile_length' => 10],
            ['name' => 'Vietnam', 'mobile_code' => '+84', 'mobile_length' => 9],
            ['name' => 'Wallis and Futuna', 'mobile_code' => '+681', 'mobile_length' => 6],
            ['name' => 'Yemen', 'mobile_code' => '+967', 'mobile_length' => 9],
            ['name' => 'Zambia', 'mobile_code' => '+260', 'mobile_length' => 9],
            ['name' => 'Zimbabwe', 'mobile_code' => '+263', 'mobile_length' => 9]
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name' => $country['name'],
                'mobile_code' => $country['mobile_code'],
                'mobile_length' => $country['mobile_length'],
            ]);
        }
    }
}
